version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:42.16.1-unstable
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Reads STEAMAPPBRANCH from your .env file to set the build version (ARG).
        - STEAMAPPBRANCH=${STEAMAPPBRANCH}
    env_file:
      - .env
    environment:
      WORKSHOP_IDS: '3682136459;3268487204;3635333613;3695670830;3469292499;3693258802;3414634809;3429790870;2447729538;2463184726;2684285534;2812326159;3396622780;2850935956;3470426196;3343810046;3281755175;3403490889;3431734923;2787539183;3671351750;3470422050;3402491515;3304582091;2983905789;3543229299;3110911330;3171167894;3670064951;3614034284;3396446795;3428146910'
      MOD_IDS: '\\PROJECTRVInterior42;\\ReflectionEnabler;\\MoodleFramework;\\tsarslib;\\damnlib;\\87fordB700;\\KI5campers;\\85chevyStepVan;\\WashOrRot;\\WanderingZombiesWIP;\\Bandits2;\\DynamicTradingCommon;\\DynamicTradingV2;\\DynamicColonies;\\BanditsCreator;\\TacHold Complete;\\FH;\\SPNCC;\\SPNCCDetails;\\SPNCCDetailsHD;\\SPNCCFaces;\\SpnHair;\\SpnCloth;\\SpnOpenCloth;\\TombBody;\\TombBodyCustom;\\TombBodyTex;\\LilliesEnhancedMilitaryClothes;\\LilliesEnhancedMilitaryClothesTextures;\\KATTAJ1_ClothesCore;\\KATTAJ1_Military;\\VanillaVehiclesAnimated;\\StandardizedVehicleUpgrades3Core;\\StandardizedVehicleUpgrades3V;\\VanillaVehiclesAnimated_SVU;\\SM4BootsExpandedB42;\\SM4BootsExpandedFlatshoes;\\YakiHRB42;\\HardwoodsTurnoutGear;\\TombBodyCompat;\\TombBodyCompatBootsExp'
      SERVERNAME: rhapsoboid
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      # Server data
      - ./data:/home/steam/Zomboid
      # Workshop mods folder
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
      # Reflection Enabler
      - ./workshop-mods/content/108600/3682136459/mods/reflection-enabler/zombie:/home/steam/pz-dedicated/zombie
      # For custom maps
