# Enabled Mods - load order matters
enabled_mods:
  # Libraries
  - zdk
  - ZModUnbork
  - PROJECTRVInterior42
  - ReflectionEnabler
  - MoodleFramework
  - tsarslib
  - damnlib
  - errorMagnifier
  - ChuckleberryFinnAlertSystem

  # Vehicles
  - 87fordB700
  - KI5campers
  - 85chevyStepVan

  # Vehicle Upgrades
  - VanillaVehiclesAnimated
  - StandardizedVehicleUpgrades3Core
  - StandardizedVehicleUpgrades3V
  - VanillaVehiclesAnimated_SVU

  # Mechanics & Content
  - WashOrRot
  - SkillRecoveryJournal
  - ammomaker
  - HBVCEFb42
  - FWOFitnessWorkoutOverhaul
  - FWOBenchPress&Treadmill

  # AI
  - WanderingZombiesWIP
  - Bandits2
  - DynamicTradingCommon
  - DynamicTradingV2
  - DynamicColonies
  - BanditsCreator

  # Animations
  - TacHold Complete

  # Clothing & Cosmetics
  - HereGoesTheSun
  - FH # Fluffy Hair
  - SPNCC
  - SPNCCDetails
  - SPNCCDetailsHD
  - SPNCCFaces
  - SpnHair
  - SpnCloth
  - SpnOpenCloth
  - TombBody
  - TombBodyCustom
  - TombBodyTex
  - LilliesEnhancedMilitaryClothes
  - LilliesEnhancedMilitaryClothesTextures
  - KATTAJ1_ClothesCore
  - KATTAJ1_Military
  - SM4BootsExpandedB42
  - SM4BootsExpandedFlatshoes
  - YakiHRB42
  - HardwoodsTurnoutGear
  - TombBodyCompat
  - TombBodyCompatBootsExp

# Enable Maps - load order matters
enabled_maps:
  - map_distanciado # Required for RV Interior to work
  - Muldraugh, KY

# Workshop subscriptions
workshop_ids:
  - 3682136459  # [B42] Reflection Enabler
  - 3268487204  # [B42] Bandits NPC
  - 3635333613  # [B42] Dynamic Trading
  - 3695670830  # [B42] ZedColonies - Dynamic Trading Addon
  - 3469292499  # [B42] Bandits Creator
  - 3693258802  # Tactical Hold Complete
  - 3414634809  # Spongie's Character Customisation
  - 3429790870  # Tomb's Player Body Overhaul
  - 2447729538  # Fluffy Hair [B41 & B42ish]
  - 2463184726  # Spongie's Hair
  - 2684285534  # Spongie's Clothing
  - 2812326159  # Spongie's Open Jackets
  - 3396622780  # Lillie's Enhanced Militaria
  - 2850935956  # Boots Expanded 11 for B41 and B42 (42.15 quickfix)
  - 3470426196  # KATTAJ1 Military Pack [B41/B42MP]
  - 3281755175  # Vanilla vehicles animated
  - 3403490889  # Standardized Vehicle Upgrades 3 - Core - B42
  - 3304582091  # Standardized Vehicle Upgrades 3 - Vanilla Addon
  - 3431734923  # Tomb's Player Body Overhaul - Compatibility
  - 2787539183  # Yaki's Hair Retexture
  - 3671351750  # Hardwood's FireFighter's Finery
  - 3470422050  # KATTAJ1 Clothes Core [B41/B42MP]
  - 3402491515  # Tsar's Common Library B42
  - 2983905789  # Wandering Zombies
  - 3543229299  # [B42]Project RV Interior
  - 3110911330  # '87 Ford B700/F700 Trucks
  - 3171167894  # that DAMN Library
  - 3670064951  # Campers!
  - 3614034284  # '85 Chevrolet Step-Van
  - 3396446795  # Moodle Framework
  - 3428146910  # Wash Or Rot
  - 2896041179  # errorMagnifier
  - 3077900375  # Mod Update and Alert System
  - 2503622437  # Skill Recovery Journal
  - 2788256295  # Ammo Maker
  - 3610677934  # HBVCEFb42
  - 2940354599  # Fitness & Workout Overhaul
  - 3618557184  # Here Goes the Sun [B42MP]
  - 3690770492  # zdk
  - 3677147974  # Zed's Universal Mod Unbork